### ISSUE TITLE
pre-commit: yamllint configuration itself isn't checked

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [adrienverge/yamllint#113]
Currently, yamllint configuration isn't checked by the yamllint pre-commit hook as it doesn't have the `yaml` tag identified.  [The PR of adding it has been merged to the identify library](https://github.com/chriskuehl/identify/commit/0e675775d40cf7d4914100a77f9263910c0657a7#diff-ee09a186de2e9e07dbcbad2aac80cc79), until it becomes effective one can use the following pre-commit config to make it check yamllint configurations.

```yaml
%YAML 1.2
---
# pre-commit Framework Configuration
# https://pre-commit.com/
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: master
    hooks:
      - id: yamllint
        files: \.(yaml|yml|yamllint)$
        types: [file, yaml]
...
```
