### ISSUE TITLE
Invalid duplicate key << error

### ISSUE THREAD

**Issue by jayvdb** [adrienverge/yamllint#134]
In the following yaml (.gitlab-ci.yml), `<<` is not a duplicate key.  It merges the mappings.

```yaml
.test_env: &test_env
  stage: test
  cache:
    key: test
    paths:
      - .cache/pip

.collect_artifacts: &collect_artifacts
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - public

build:
  <<: *test_env
  <<: *collect_artifacts
  stage: build
  before_script:
    - pip install -r requirements.txt
  script:
    - ./.ci/build.sh
```
