### ISSUE TITLE
line-length does not work with Unicode characters

### ISSUE THREAD

**Issue by yggi49** [adrienverge/yamllint#146]
I have the following UTF-8-encoded document:

```yaml
---
# This is a test to check if “line-length” works nice with unicode characters
check: 1
foo: 'This is another quick test to check behavior with “unicode characters”'
```

Note that the comment in line two as well as the string in line four both contain a Unicode left double quotation mark (U+201C) and a Unicode right double quotation mark (U+201D).  Both lines are 77 characters long, yet yamllint reports “line too long” errors:

```console
% yamllint test.yml
test.yml
  2:81      error    line too long (81 > 80 characters)  (line-length)
  4:81      error    line too long (81 > 80 characters)  (line-length)
% yamllint --version
yamllint 1.13.0
```

It seems as if yamllint counts bytes, not characters, as each Unicode quotation character takes up three bytes when UTF-8 encoded.

_Note: this occurs when running yamllint in a Python 2 environment.  I have not tested it with Python 3, which for my specific use case is not an option yet._
