### ISSUE TITLE
How to lint "JSON with comments"

### ISSUE THREAD

**Issue by eyalev** [adrienverge/yamllint#186]
I want to achieve linting for YAML that will look like "JSON with comments".

Example:

```
# First comment
{
  # Second comment
  key1: "value1",
  key2: "value2",
  object1: {
    object1_key1: "value1", # Inline comment
    object1_list1: ["one", "two", "three"],
    object1_key2: "value1"
  },
  list2: [
    # Another comment
    "one",
    "two",
    43,
    "three",
    true
  ],
  key3: "value3"
}
```

My current issue is to require using braces and brackets for "objects" and "lists".

Is there a way to enforce this?

Thanks

**Comment by adrienverge** [comment]
Hi @eyalev, interesting use case!

It is not possible currently, but we can imagine new options like `force` and `forbid` (to force JSON-style, or to forbid it):
```yaml
rules:
  braces:
    force: true
    min-spaces-inside: 0
    max-spaces-inside: -1
  brackets:
    force: true
    min-spaces-inside: 0
    max-spaces-inside: -1
```

Contributions are welcome. I think it's doable by detecting the usage of `BlockMappingStartToken`, `BlockSequenceStartToken`, `FlowMappingStartToken`, `FlowSequenceStartToken`.
