### ISSUE TITLE
Feature Request:  min-spaces-after check for hyphens

### ISSUE THREAD

**Issue by Pahanda** [adrienverge/yamllint#197]
I'm trying to lint an AWS configmap, and it's super strict (even more than `--strict`).

For example, this is considered invalid:
```
     -userarn: arn:aws:iam::1234567890123:user/WinstonSmith
       username: WinstonSmith
       groups:
        - system:clusterRW
```
It actually wants this:
```
     - userarn: arn:aws:iam::1234567890123:user/WinstonSmith
       username: WinstonSmith
       groups:
        - system:clusterRW
```
This was the result of a typo on the part of one of our admins, but because it passed linting, it ended up clobbering our config, requiring the cluster owner to fix things.

I'm familiar with the `max-spaces-after` value for `hyphens`.  I'd love to be able to have a `min-spaces-after` value, to catch things like this.  Or maybe a `spaces-after` value that would be enforced by the linter.

I'm going to try adding this myself (just for fun), but it would be nice to have an official one.
