### ISSUE TITLE
[BUG] Default setting (`enable`) of `empty-values` & `octal-values` does nothing

### ISSUE THREAD

**Issue by myii** [adrienverge/yamllint#204]
There appears to be a contradiction between the meaning of `enable` in the default settings and the actual end result.

#### `empty-values`

https://github.com/adrienverge/yamllint/blob/b62b424dd43acd4b0e08f46f49d88bc15461384e/yamllint/conf/default.yaml#L21

https://github.com/adrienverge/yamllint/blob/0f073f7a09d29ceb85a1aaf388bdbe5f4145f869/yamllint/rules/empty_values.py#L78-L79

#### `octal-values`

https://github.com/adrienverge/yamllint/blob/b62b424dd43acd4b0e08f46f49d88bc15461384e/yamllint/conf/default.yaml#L29

https://github.com/adrienverge/yamllint/blob/0f073f7a09d29ceb85a1aaf388bdbe5f4145f869/yamllint/rules/octal_values.py#L69-L70

---

In both cases, the only way to get these working is to specify them in the `.yamllint` file:

```yaml
rules:
  empty-values:
    forbid-in-block-mappings: true
    forbid-in-flow-mappings: true
  octal-values:
    forbid-implicit-octal: true
    forbid-explicit-octal: true
```

What is `enable` supposed to do?  Otherwise, isn't the default actually `disable` in both cases, with `default.yaml` needing updating (with the knock-on affect to the documentation)?
