### ISSUE TITLE
Bug: Quoted strings rule doesn't detect unquoted strings in array

### ISSUE THREAD

**Issue by mmerfort** [adrienverge/yamllint#208]
Hello,

I noticed that yamllint does not detect unquoted strings in an array even though this rule has been enabled:

### testfile.yaml
```yaml
---
bla:
  - FOO
  - BAR
  - BAZ
```
### configuration.yaml
```yaml
---
extends: 'default'

rules:
  quoted-strings:
    quote-type: 'single'
```

I tried using different quote-types but none of them seem to work.

Thanks in advance.
