### ISSUE TITLE
Disable in comment - trouble in GitHub Action

### ISSUE THREAD

**Issue by JonGilmore** [adrienverge/yamllint#214]
I'm attempting to disable line-length in a comment in a GitHub action, but I don't seem to be having any luck with it. Is there something obvious that I'm missing here? I've seen others use this in their examples, but I can't seem to get it to work as expected.
```
---
name: CI
# yamllint disable-line rule:line-length
on:
  push:

jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - name: Getting your configuration from GitHub
        uses: actions/checkout@v1
      - name: Running YAMLlint
        uses: "docker://pipelinecomponents/yamllint:latest"
        with:
          args: yamllint .
```

Results:
![image](https://user-images.githubusercontent.com/7232986/69502058-97251e00-0ed0-11ea-9358-bf3197e568b6.png)
