### ISSUE TITLE
Bug: quoted-strings rule not working for strings with values matching boolean or number scalars

### ISSUE THREAD

**Issue by ruipinge** [adrienverge/yamllint#233]
Hi,

Given the following `.yamllint` config:

```
extends: default
rules:
    quoted-strings:
        quote-type: single
```

and the yaml file:
```
---
string0: "true"
string1: 'false'
boolean0: true
```

the rule `quoted-strings` should fail on line 2. It doesn't because the string value matches a boolean scalar (although it's actually a string). It also happens for numbers, nulls, and any scalar values.
