### ISSUE TITLE
`quoted-strings` only-when-needed incorrectly detecting strings with redundant quotes

### ISSUE THREAD

**Issue by RealOrangeOne** [adrienverge/yamllint#242]
Since upgrading to 1.21.0, I enabled the following config:

```yaml
  quoted-strings:
    quote-type: double
    required: only-when-needed
```

Unfortunately, seems there's some strings which it believes don't need quoting, when in fact they do:

- `aur_builder ALL=(ALL) NOPASSWD: /usr/bin/pacman`
- `%H:%M:%S`
- `'Mac' in ansible_facts.product_name`

It seems to be something around when a string either contains or starts with a special character, but isn't entirely a special character?
