### ISSUE TITLE
Unable to control parsable format from configuration file

### ISSUE THREAD

**Issue by ssbarnea** [adrienverge/yamllint#266]
In order to make the format compatible with other similar tools, I wanted chage the config to always use parsable but adding `format: parsable` to the config does not work.

I looked at the code and apparently there is no support to control parsable via configuration file.

**Comment by adrienverge** [comment]
Sounds like a good addition! Do you want to solve this problem?

This could look like this:
```yaml
extends: default

format: parsable  # ←

ignore: |
  *.dont-lint-me.yaml

rules:
  key-duplicates: enable
```
