### ISSUE TITLE
max line-length from custom conf file not being applied

### ISSUE THREAD

**Issue by MMollyy** [adrienverge/yamllint#293]
Hi,
I've got a custom conf file from which I am extending onto the default:
```
---

# This is my first, very own configuration file for yamllint!
# It extends the default conf by adjusting some options.

extends: default
rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 1
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
    min-spaces-inside-empty: -1
    max-spaces-inside-empty: -1
  colons:
  min-spaces-after: 0
    max-spaces-before: 0
    max-spaces-after: 1
  commas:
    max-spaces-before: 0
    min-spaces-after: 0
    max-spaces-after: 0
  comments:
    require-starting-space: true
    min-spaces-from-content: 2
  document-start:
    present: true
  empty-lines:
    max: 2
    max-start: 0
    max-end: 0
  empty-values: enable
    forbid-in-block-mappings: false
    forbid-in-flow-mappings: false
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: consistent
    indent-sequences: true
    check-multi-line-strings: false
  key-duplicates: enable
  key-ordering: disable
  line-length:
    max: 150
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  new-lines:
    type: unix
  octal-values: enable
    forbid-implicit-octal: false
    forbid-explicit-octal: false
  key-duplicates: enable
```

All of the rules are being accepted and being applied onto the yaml-files that I am verifying onto. Except, the line-length isn't being applied.
It keeps popping up with errors that line-length cannot be longer than 80 characters, example:
```
477:81    error    line too long (145 > 80 characters)  (line-length)
  482:81    error    line too long (90 > 80 characters)  (line-length)
```

python --version
Python 3.7.3

I've got no clue what else to look at what could be the issue that this single rule would not be applied. Anyone got an idea?

**Comment by anhuong** [comment]
I'm hitting a similar problem but with `empty-lines`.  I have the config set to allow max 3 empty lines but it shows that error `3 > 0 (empty-lines)`

yamllint version 1.24.2

.yamllint
``yaml
extends: default

rules:
  braces:
    max-spaces-inside: 1
    level: error
  brackets:
    max-spaces-inside: 1
    level: error
  colons:
    max-spaces-after: -1
    level: error
  commas:
    max-spaces-after: -1
    level: error
  comments: disable
  comments-indentation: disable
  document-start: disable
  empty-lines:
    max: 10
    level: error
```

```sh
$ yamllint .
./defaults/main.yml
  49:1      error    too many blank lines (3 > 0)  (empty-lines)
```

Contents of `/defaults/main.yml`
```yaml
---
# defaults file for sch
default:
  sch:
    chart:
      app_name: ""
      label_type: non-prefixed
      secret_gen:
        suffix: "generated"
        secrets: []
    names:
      full_name:
        max_length: 63
        release_name_trunc_length: 42
        app_name_trunc_length: 20
        comp_name_trunc_length: 0
      full_comp_name:
        max_length: 63
        release_name_trunc_length: 36
        app_name_trunc_length: 13
        comp_name_trunc_length: 12
      stateful_set_name:
        max_length: 33
        release_name_trunc_length: 15
        app_name_trunc_length: 7
        comp_name_trunc_length: 9



```
Notice 3 lines at the end. Even when I change the config to allow max 10 empty lines or input the config via the `-d` flag in the commandline, I still see the same error. It looks like its still using the default value of 0.
