### ISSUE TITLE
Wrong indentation: expected 6 but found 8 (indentation)

### ISSUE THREAD

**Issue by adoyle-h** [adrienverge/yamllint#35]
```yaml
---
- a:
    map:
        key: true
- b:
    map: false
```

I expect the snippet passed. But yamllint shows failure that "Wrong indentation: expected 6 but found 8 (indentation)" at line 4.

My yamllint configuration: 

```yaml
---
extends: default

rules:
    indentation:
        spaces: consistent
        indent-sequences: whatever
        check-multi-line-strings: true
```

Is there something wrong?
