### ISSUE TITLE
Bug: Confict between required quoted strings and explicit octal

### ISSUE THREAD

**Issue by scolby33** [adrienverge/yamllint#351]
There appears to be a conflict between `octal-values.forbid-explicit-octal = false` and `quoted-strings.required = true`.

## Setup

.yamllint.yaml:
```yaml
---
rules:
  octal-values:
    forbid-explicit-octal: false
  quoted-strings:
    required: true
...
```

test.yaml:
```yaml
---
foo: 0o100
...
```

```console
$ yamllint test.yaml
test.yaml
  2:6       error    string value is not quoted with any quotes  (quoted-strings)
```

## What Happens

yamllint reports an error because it thinks the value of the `foo` key is a string.

## What I Expect to Happen

yamllint should accept the value of the `foo` key as an explicit octal integer equal to decimal 64.
