### ISSUE TITLE
Import ignores from .gitignore

### ISSUE THREAD

**Issue by sandstrom** [adrienverge/yamllint#360]
## Problem

Right now there is a lot of duplication between our yaml-lint ignore directives, and our .gitignore files. It would be neat if we could import from gitignore, via e.g. `import_ignore: .gitignore`.

## How it could work

Something like:

```yaml
# using the default rules
extends: default

# skip everything ignored by .gitignore
import_ignore: ".gitignore"

rules:
  octal-values: enable
  # …
```

Since I think yaml-lint is using the same ignore format as .gitignore, maybe it's fairly easy to import? Would also allow keeping the ignore list in a separate file.

## Open Questions
- How should conflicting rules be solved? Ideally with "last rule wins". That way one can override or adjust directives imported from .gitignore if needed.
