### ISSUE TITLE
Rule 'comments' should ignore Cloud-Init "#cloud-config" similar to shebangs

### ISSUE THREAD

**Issue by lwbt** [adrienverge/yamllint#361]
I noticed that shebangs can be configured to be ignored in recent versions. Cloud-Init has a similar string at the start of a document which should be also ignored: `#cloud-config`

https://cloudinit.readthedocs.io/en/latest/topics/examples.html?highlight=%23cloud-config

**Comment by adrienverge** [comment]
It makes sense. However there will probably be other magic values `#foo` in the future. Maybe the best would be to specify the list of regex to ignore?
```yaml
rules:
  comments:
    require-starting-space: true
    ignore-regex:
      - ^#!
      - ^#cloud-config
    min-spaces-from-content: 2
```
