### ISSUE TITLE
Not indenting array is not an error

### ISSUE THREAD

**Issue by rwxrob** [adrienverge/yamllint#374]
The following is being incorrectly flagged as an error:

```yaml
AnArray:
- Title: This is Fine
  Comment: Stop reporting this as an error
- Title: Considerations
  Comment: People should RTFS before making a "linter"
```

That is all.
