### ISSUE TITLE
comments-indentation: comment not indented like content should issue an error

### ISSUE THREAD

**Issue by pmalek-sumo** [adrienverge/yamllint#375]
I believe the following yaml: 

```yaml
## Random stuff

stuff:
  ## uncomment for the debug mode
  # debug: true
```

should cause an error like this:

```
  4:3       error    comment not indented like content  (comments-indentation)
```

Config used:

```yaml
extends: relaxed

rules:
    comments: enable
    comments-indentation: enable

    line-length:
        max: 140
        level: warning

    indentation:
        level: warning
        indent-sequences: consistent
```

**Comment by adrienverge** [comment]
I guess you meant "*should **not** cause an error like this*"?

This is probably a very subjective topic, depending on how you "see" and "feel" YAML.

I kind of agree with what you say. However, some others users would dislike such a change, because it would mean this wrongly-indented comment wouldn't be reported:
```yaml
todo list:
  item 1:
  item 2: ✓
  item 3:
    # item 4:
  item 5:
  item 6: ✓
```
