### ISSUE TITLE
Feature Question spaces in quoted strings

### ISSUE THREAD

**Issue by suckowbiz** [adrienverge/yamllint#389]
Hi,

first I would like to thank you for `yamllint`. I always use it to increase quality for automated CI/CD pipelines in enterprise environments, when any YAML is involved.

Was it ever intended to lint leading and trailing spaces in quoted strings?

Examples

- This one would fail:
```yaml
hello: ' world'
world: 'hello '
yaml: ' lint '
```

- This would succeed
```yaml
hello: 'world'
world: 'hello'
yaml: 'lint'
```

Is this a feature that would make sense or is it not implemented for a reason?
