### ISSUE TITLE
yamllint allows referencing a non-existant anchor 

### ISSUE THREAD

**Issue by mckaymatt** [adrienverge/yamllint#395]
yamllint 1.26.1 (latest) does not flag references to anchors that don't exist.

```yaml
---
foo: &foo
    keyA: value1

bar:
    <<: *no_anchor_with_this_name
    keyB: value2
```

If you try to parse this using a tool like PyYAML it errors.

```
  File ".local/lib/python3.8/site-packages/ruamel/yaml/composer.py", line 115, in compose_node
    raise ComposerError(
ruamel.yaml.composer.ComposerError: found undefined alias 'no_anchor_with_this_name'
  in "test.yaml", line 6, column 9

```

**Comment by adrienverge** [comment]
Hello,

Indeed yamllint does not currently detect inexistent anchors, or unmatching aliases.

It could be implemented in a new yamllint rule. In theory, it should be possible if aliases aren't used before anchors are declared (and this seems to be the case according to the [YAML specification 6.9.2.](https://yaml.org/spec/1.2/spec.html#id2785586): "*An anchor marks a node for *future* reference*").

**Comment by amimas** [comment]
I'd also like to check if there are unused anchors in the yaml files. Is this rule being considered for yamllint?

**Comment by adrienverge** [comment]
Yes, I think this is within the scope of a YAML linter. An option like `forbid-unused-anchors` could do the job.

In the end, a new rule like this would be great:

```yaml
rules:
  anchors:
    forbid-unknown-aliases: true      # true by default, because YAML spec fordids it
    forbid-duplicated-anchors: false  # false by default, because YAML spec allows it
    forbid-unused-anchors: false      # false by default, because YAML spec allows it
```
