### ISSUE TITLE
Feature request (not really an issue)

### ISSUE THREAD

**Issue by tsigouris007** [adrienverge/yamllint#402]
Could there be a custom rule for custom linting such as:
```
extends: default
rules:
  custom:
    path: /test/yourfile2.js
    line: 1
    column: 1
    message: 'Dangerous function innerHTML'
    path: /test/youfile.js
    line: 5
    column: 15
    message: 'Unfiltered input'
```
Could not find anywhere else to request this so I opened it here.
