### ISSUE TITLE
Using custom config file on pre-commit

### ISSUE THREAD

**Issue by carlosbio** [adrienverge/yamllint#410]
Hi! I'm trying to configure my .pre-commit-config.yaml file to run yamllint using a custom .yamllint.yaml config file that lives at the root of the project, but I'm not being able to do it.

So far, the .pre-commit-config.yaml file looks like this:

```
repos:
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: ['-c ${workspaceFolder}/.yamllint.yaml .']
```

I already tried removing the ${workspaceFolder} reference and I also don't want to use the real path, since the project can be used in different machines.

Any advice?

Cheers!
