### ISSUE TITLE
unknown option "check-keys" for rule "truthy"

### ISSUE THREAD

**Issue by Shrimpstronaut** [adrienverge/yamllint#433]
# Issue
I'm currently getting this error when executing ymllint locally:

```
invalid config: unknown option "check-keys" for rule "truthy"
The terminal process "zsh '-c', 'npm run lint:yml'" terminated with exit code: 255.
```

# Setup / environment

`yamllint 1.20.0`

Config:

```
  
---
# Extends the default conf by adjusting some options.

extends: default

rules:
  empty-lines: disable
  line-length: disable
  truthy:
    allowed-values: ['true', 'false', 'True', 'False', 'yes', 'no']
    check-keys: true
  indentation:
    spaces: consistent
    indent-sequences: whatever
    check-multi-line-strings: false
```

# Reproduce

When executing `yamllint .` I'm getting the error above.
When I remove the `check-keys` option, it works as expected.

Any help and support is much appreciated!
