### ISSUE TITLE
indentation.spaces ignored, when using tag and anchor

### ISSUE THREAD

**Issue by bartsch** [adrienverge/yamllint#435]
(yamllint 1.26.3)

Having a tag and an anchor in an example.yaml like this:
```yaml
---
pretty: !useless &example
    purpose: trigger indentation error
```
and running yamllint:
`yamllint --config-data "{extends: default, rules: {indentation: {spaces: 4}}}" example.yaml`
raises the error:
```
example.yaml
  3:5       error    wrong indentation: expected 8 but found 4  (indentation)
```

So, it ignores `spaces: 4` and wants _purpose_ to be aligned with the tag at column 8.
- Swapping the tag and anchor doesn't change the result - the error remains the same.
- Removing either tag or anchor works.
