### ISSUE TITLE
Specify `yaml-files` without config (with pre-commit)?

### ISSUE THREAD

**Issue by jamesbraza** [adrienverge/yamllint#459]
I am trying to run yamllint on a [`CITATION.cff`](https://citation-file-format.github.io/) file.  I believe I need to use the `yaml-files` option.

Note I am using `pre-commit` with this config:

```yaml
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args:
          - "--strict"
```

Is it possible to somehow add `yaml-files` to the `pre-commit` config to append `CITATION.cff` to the list?  I have tried a few permutations of syntax to no luck :/

**Comment by adrienverge** [comment]
Hello,

Your question seems related to pre-commit. I suggest using a community-powered Q&A service, like Stack Overflow for topics like this. (This issue tracker is only meant for issues regarding yamllint, and either I don't fully get your problem, or it's not really about yamllint itself.)

Thank you!

**Comment by jamesbraza** [comment]
Yes for what it's worth, I had actually checked for a `[yamllint]` tag on stack overflow ([search](https://stackoverflow.com/questions/tagged/yamllint)) and didn't see anything.  I also searched through the GitHub issues here.

I do think this is a yamllint question, really it's a yamllint command-line question (since `pre-commit` just wraps that).

I read around and discovered from [Running yamllint docs](https://yamllint.readthedocs.io/en/stable/quickstart.html#running-yamllint) that I can actually invoke yamllint from the command line.  From `yamllint --help` I realized there is not a command-line argument like `--yaml-files`.  `yaml-files` appears to be a config-only option.

In order for me to pass `CITATION.cff` to `yamllint`, I need add `'*.cff'` to `yaml-files`.  Am I correct that the only way I can make that happen is via the creation of a `.yamllint` config file (and not a CLI argument)?

**Comment by andrewimeson** [comment]
This works. There might be a better way.

```yaml
---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        args:
          - --strict
        types: [file]
        files: \.(cff|yml|yaml)$
```
