### ISSUE TITLE
disable or disable-line has no effect on the file with helm blocks

### ISSUE THREAD

**Issue by dmitry-mightydevops** [adrienverge/yamllint#460]
```yaml
{{- if .Values.efs.enabled -}} # yamllint disable
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-efs-csi-driver
  namespace: argo-cd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  project: default
  source:
    chart: aws-efs-csi-driver
    helm:
      values: |
        # you can obtain the fileSystemId with
        # aws efs describe-file-systems --query "FileSystems[*].FileSystemId"
        storageClasses:
          - name: efs
            parameters:
              provisioningMode: efs-ap
              fileSystemId: {{ .Values.efs.fileSystemId }}
              directoryPerms: "777"
              gidRangeStart: "1000"
              gidRangeEnd: "2000"
              basePath: "/snapshots"

        # enable it after the following issue is resolved
        # https://github.com/bitnami/charts/issues/7769
        # node:
        #   nodeSelector:
        #     etcd: "true"

    repoURL:  https://kubernetes-sigs.github.io/aws-efs-csi-driver/
    targetRevision: {{ .Values.efs.chartVersion }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

 {{- end }}
```

I'm getting this 

```
➜ git commit -m "feat: add yamllint"
check for added large files..............................................Passed
check for merge conflicts................................................Passed
forbid new submodules................................(no files to check)Skipped
don't commit to branch...................................................Passed
check for broken symlinks............................(no files to check)Skipped
mixed line ending........................................................Passed
fix end of files.........................................................Passed
trim trailing whitespace.................................................Passed
check for case conflicts.................................................Passed
yamllint.................................................................Failed
- hook id: yamllint
- exit code: 1

.pre-commit-config.yaml
  7:1       error    wrong indentation: expected 2 but found 0  (indentation)

staging/argocd/apps/templates/aws-efs-csi-driver.yaml
  1:3       error    syntax error: expected the node content, but found '-' (syntax)


```
