### ISSUE TITLE
Can't ignore spercific line

### ISSUE THREAD

**Issue by Alexhha** [adrienverge/yamllint#462]
We have the following yaml file
```
    logging:
# yamllint disable-line
%{ if cloudwatch_enabled == "true" ~}
      driver: awslogs
      options:
        awslogs-region: eu-west-1
        awslogs-group: pdn-infra
        awslogs-stream: ${node_id}
%{ else ~}
      driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
%{ endif ~}
```
But I still get syntax error
```
$ yamllint -d '{extends: default, rules: {line-length: {max: 128}, document-start: disable, empty-lines: disable}}' docker-compose.tftpl
docker-compose.tftpl
  45:2      error    syntax error: expected alphabetic or numeric character, but found '{' (syntax)
```
Did I miss something ? How can I ignore terraform template syntax `%{ if }...%{ else }...%{ endif }` ?

P.S.
```
$ yamllint -v
yamllint 1.26.3
```

**Comment by perlpunk** [comment]
that's basically the same issue as rhe recent #460

**Comment by Alexhha** [comment]
Haven't seen the issue. Have I correctly understood - there is no way to skip checks just for 1 line in such case ?

**Comment by Alexhha** [comment]
@andrewimeson 

Unfortunately it doesn't work in such way. Got the following result
```
    logging:
      #       driver: json-file
      options:
        max-size: "50m"
        max-file: "10"
    #     ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000
```
