### ISSUE TITLE
yamllint indentation rules are not compatible with `esbenp.prettier-vscode` or `redhat.vscode-yaml`

### ISSUE THREAD

**Issue by DeadNews** [adrienverge/yamllint#492]
Example from [ansible docs](https://docs.ansible.com/ansible/latest/user_guide/playbooks_loops.html#iterating-over-a-list-of-hashes):

`test1.yml`:
```yml
---
- name: Test
  hosts: localhost

  tasks:
    - name: Add several users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
      loop:
        - { name: "testuser1", groups: "wheel" }
        - { name: "testuser2", groups: "root" }
```
```sh
❯ yamllint test1.yml
test1.yml
  12:12     error    too many spaces inside braces  (braces)
  12:47     error    too many spaces inside braces  (braces)
  13:12     error    too many spaces inside braces  (braces)
  13:46     error    too many spaces inside braces  (braces)
```

`test2.yml` with long strings:
```yml
---
- name: Test
  hosts: localhost

  tasks:
    - name: Add several users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
      loop:
        - { name: "veryveryveryverylonguser1", groups: "veryveryveryverylongwheel" }
        - { name: "veryveryveryverylonguser2", groups: "veryveryveryverylongroot" }
```
```sh
❯ yamllint test2.yml
test2.yml
  12:12     error    too many spaces inside braces  (braces)
  12:83     error    too many spaces inside braces  (braces)
  12:81     error    line too long (84 > 80 characters)  (line-length)
  13:12     error    too many spaces inside braces  (braces)
  13:82     error    too many spaces inside braces  (braces)
  13:81     error    line too long (83 > 80 characters)  (line-length)
```

`test3.yml` after formatting with [esbenp.prettier-vscode](https://github.com/prettier/prettier-vscode) or [redhat.vscode-yaml](https://github.com/redhat-developer/vscode-yaml):
```yml
---
- name: Test
  hosts: localhost

  tasks:
    - name: Add several users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
      loop:
        - {
            name: "veryveryveryverylonguser1",
            groups: "veryveryveryverylongwheel",
          }
        - {
            name: "veryveryveryverylonguser2",
            groups: "veryveryveryverylongroot",
          }
```
```sh
❯ yamllint test3.yml
test3.yml
  13:13     error    wrong indentation: expected 10 but found 12  (indentation)
  14:13     error    wrong indentation: expected 10 but found 12  (indentation)
  15:11     error    wrong indentation: expected 8 but found 10  (indentation)
  17:13     error    wrong indentation: expected 10 but found 12  (indentation)
  18:13     error    wrong indentation: expected 10 but found 12  (indentation)
  19:11     error    wrong indentation: expected 8 but found 10  (indentation)
```

`test4.yml` after manual formatting:
```yml
---
- name: Test
  hosts: localhost

  tasks:
    - name: Add several users
      ansible.builtin.user:
        name: "{{ item.name }}"
        state: present
        groups: "{{ item.groups }}"
      loop:
        - {
          name: "veryveryveryverylonguser1",
          groups: "veryveryveryverylongwheel",
        }
        - {
          name: "veryveryveryverylonguser2",
          groups: "veryveryveryverylongroot",
        }
```
```sh
❯ yamllint test4.yml
❯ echo $?  
0
```

`test3.yml` is obviously prettier than `test4.yml`, isn't it?

----
Ref: https://github.com/ansible/vscode-ansible/issues/597#issuecomment-1228451789
