### ISSUE TITLE
Support exclusion of files/directories

### ISSUE THREAD

**Issue by michaelmoussa** [adrienverge/yamllint#5]
There doesn't seem to be a way to lint all files in a directory, but exclude some, for example:

```
$
└── foo
    ├── a.yml
    ├── b1.yml
    ├── b2.yml
    ├── b3.yml
    ├── c.yml
    ├── d.yml
    └── e.yml
```

Let's say that, for whatever reason, I don't care about the formatting of some of these yml files. I'd like to be able to run something along the lines of:

```
yamllint foo --exclude=c.yml
```

or

```
yamllint foo --exclude=b*.yml
```

or perhaps multiple...

```
yamllint foo --exclude=b*.yml,d.yml
```

My specific use case is a directory with a bunch of organized yml files that also includes a git submodule with some yml files that would fail linting. It's third-party code and doesn't live in our repository, so I don't need to validate it.

Alternatively, this could be configurable:

```
# .yamllint
files_or_dirs:
    include:
      - foo
      - bar
      - baz.yml
    exclude:
      - foo/b*.yml
      - bar/boo.yml
```

Thanks for sharing this library! It was very easy to get everything going.
