### ISSUE TITLE
float value bug when quoting strings only-when-needed

### ISSUE THREAD

**Issue by andreineculau** [adrienverge/yamllint#503]
The config

```yml
extends: default
rules:
  float-values:
    forbid-inf: true
    forbid-nan: true
    forbid-scientific-notation: true
    require-numeral-before-decimal: true
  quoted-strings:
    quote-type: single
    required: only-when-needed
    allow-quoted-quotes: true
```

will invalidate

```yml
color: '5319E7'
color: 5319E7
```

with

```text
./test.yml:1:8: [error] string value is redundantly quoted with single quotes (quoted-strings)
./test.yml:2:8: [error] forbidden scientific notation "5319E7" (float-values)
```
