### ISSUE TITLE
Wrong indentation error when having a sequence with anchor only

### ISSUE THREAD

**Issue by roymiloh** [adrienverge/yamllint#526]
Hey, the following is failing due to a wrong indentation:

```yaml
root:
  - &list
      - foo: 1
      - bar: 1
```

The error is:

>  3:7       error    wrong indentation: expected 4 but found 6  (indentation)

However, when I turn it into an ordinary sequence, it passes:

```yaml
root:
  - list:
      - foo: 1
      - bar: 1
```

It seems like it starts counting from the hyphen when there's an anchor **only**.

Here's another example that passes:

```yaml
root:
  - foo: &list
      - foo: 1
      - bar: 1
```

The `yamllint` version is `1.28.0`.
