### ISSUE TITLE
YAML Spec-like formatting of Sequences of Mappings

### ISSUE THREAD

**Issue by szepeviktor** [adrienverge/yamllint#527]
[Yaml Spec suggests](https://yaml.org/spec/1.2.2/#21-collections) putting key-value pairs in the next like after the dash.
```yaml
-
  name: Mark McGwire
  hr:   65
  avg:  0.278
-
  name: Sammy Sosa
  hr:   63
  avg:  0.288
```
Which I like very much 😍  (although I'm a four-space indent guy)

How could it be enforced with Yamllint?

**Comment by perlpunk** [comment]
(Just a note to clarify, the YAML spec doesn't "suggest" this as the best style, there are many other examples in the spec that use the more compact style)

**Comment by szepeviktor** [comment]
AFAIK this is the normal (non-compact) style and Highly popular compact style looks like the following.
```yaml
- name: Mark McGwire
  hr:   65
  avg:  0.278
- name: Sammy Sosa
  hr:   63
  avg:  0.288
```

The compact style is hard to read. It need an empty newline between mappings.

**Comment by adrienverge** [comment]
Hello,

Currently there isn't any yamllint rule that enforce such a notation.

Your "key-value pairs" example can be generalized with other types of data, which would give:
```yaml
-
  name: Mark McGwire
  hr:   65
  avg:  0.278
- 
  - nested
  - list
-
  string
- 
  [inline, sequence]
- 
  &anchor
  {key: value}
```
Is this consistent with what you have in mind?

If yes, we could consider a new option (for example `require-empty-first-line: true`) in the [`hyphens` rule](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.hyphens).
Would you like to implement this?

**Comment by szepeviktor** [comment]
> `require-empty-first-line: true`

That would be a dream come true!

I'm sorry, my development speed is 1 line/day.

**Comment by szepeviktor** [comment]
@adrienverge One more question if I may. Would it affect single-line item?
```yaml
on:
    pull_request:
        paths:
        - "**/*.yml"
        - "**/*.yaml"
```
Should the above be like this?
```yaml
on:
    pull_request:
        paths:
        -
            "**/*.yml"
        -
            "**/*.yaml"
```
Thank you!
