### ISSUE TITLE
BUG: line-length returns wrong number of characters when using special characters

### ISSUE THREAD

**Issue by ChristianZimpelmann** [adrienverge/yamllint#530]
The returned number of characters is wrong when using special characters like ä, ö, ü (on Windows).

I have the follwing yaml-file:

```yaml
---
check: 1
test: ä, ü, ö are special characters. Check whether they influence detected line lenght.
```

Lenth of line 3 is 88, but `yamllint test.yaml` returns:

```
3:89      error    line too long (91 > 88 characters)  (line-length)
```

Each of those three special characters seem to be counted as two characters.

Two more remarks:
- The error seems to not appear on Ubuntu
- The bug might be related to #146.
