### ISSUE TITLE
Exclude @ symbol check at value start

### ISSUE THREAD

**Issue by Dum6o** [adrienverge/yamllint#531]
I have used linter to lint spring-boot framework `application.yaml` file:
``` yaml
---
spring:
  application:
    name: @project.name@
```
`@project.name@` value allows spring-boot application to resolve application name from `pom.xml` file.
However when I run linter I get an error:
`Error: ./src/main/resources/application.yaml:4:11: [error] syntax error: found character '@' that cannot start any token (syntax)`

---

**Is there any rule how can I exclude special characters check?**
