### ISSUE TITLE
Files with all rules ignored are still parsed.

### ISSUE THREAD

**Issue by brackendawson** [adrienverge/yamllint#539]
If you ignore a file because it's very large and you don't want to spend the time linting it, you don't save any time.

# Steps to re-create
1. Make a large (like 2MB) and small yaml file and this configuration:
   ```
   small.yaml
   large.yaml
   .lint-config.yaml
   ```
   ```yaml
   extends: default
   
   ignore: |
     large.yaml
   ```
2. Run `time yamllint -c .lint-config.yaml .`
3. `rm large.yaml`
4. Run `time yamllint -c .lint-config.yaml .` again.

# Expected results
Step 2 and 4 take the same time.

# Actual results
Step 4 is a lot faster than step 2.
