### ISSUE TITLE
Allow warnings when a colon isn't followed by a space

### ISSUE THREAD

**Issue by beyarkay** [adrienverge/yamllint#563]
I recently got bit by this piece of valid-but-incorrect YAML:

```yaml
- my_object: some_value
  source: https://www.google.com
  areas:
  - {name: value, other_key: []}
  - {name:value,other_key: []}         # <-- this line in particular
  - {name:name, other_key: []}
```

because I didn't have a space after the colon for the `name` key, YAML parses this perfectly fine. I realise that requiring a space after a colon isn't always desirable becuase sometimes you want an actual colon (like in `https://www.google.com`), but is there an option which would warn about non-quoted strings with potentially confusing special characters?

For example, these would cause warnings: `{name:value}`, `https://www.google.com` because what they mean to YAML might not be what the user intended, and would recommend either quoting the special character: `{"name:value"}`, `"https://www.google.com"`, or using a space: `{name: value}`, `https: //www.google.com`

See also [this Stack overflow question](https://stackoverflow.com/questions/42124227/why-does-the-yaml-spec-mandate-a-space-after-the-colon), which conveys that this is a common misconception.
