### ISSUE TITLE
Need rules to enforce string quoting for keys

### ISSUE THREAD

**Issue by HenryGessau** [adrienverge/yamllint#617]
The current `quoted-strings` rule does not check keys.

Consider:
```yaml
---
one: 1
'two': 2
"three": 3
["a", b]: 4
{'a': a, b: 'b'}: 5
```
There is currently no rule to enforce consistent quoting for key strings.

The `quoted-strings` rule can be extended with an option to also check keys.
However, there may be a need to have different quoting rules for key strings and value strings.
