### ISSUE TITLE
Optional extended detection in key-duplicates 

### ISSUE THREAD

**Issue by fenuks** [adrienverge/yamllint#649]
Let's say I have this yaml document.

```yml
logging.level.root: DEBUG
logging.level.org.springframework: INFO

logging:
  level:
    root: DEBUG
    org.springframework: INFO
```

In generated JSON

```json
{
  "logging.level.root": "DEBUG",
  "logging.level.org.springframework": "INFO",
  "logging": {
    "level": {
      "root": "DEBUG",
      "org.springframework": "INFO"
    }
  }
}
```

no key is duplicated.

However, some programs, e.g. spring-based allow user to use second form so common prefix is written only once. Logically these are duplicates, so I wonder if `key-duplicates` rule could have option to enable detection of this, or this is too specific?
