### ISSUE TITLE
feature: add ability to have in one config file multiple configs for different paths

### ISSUE THREAD

**Issue by marcindabrowski** [adrienverge/yamllint#670]
It would be great to give ability to define different configuration for different paths in one config file, ie:

```yaml
---

extends: default

yaml-files:
  - '*.yaml'
  - '*.yml'
  - '.yamllint'

rules:
  # default rules for all files in directory

---

yaml-files:
  - 'folder1/*.yaml'

rules:
  # rules that overrides some config flags for all yamls in folder1
```

I'm aware that I can run `yamllint` with different configs for different sets of files, but this approach could simplify the usage.

Why I want this change?
Because the problem with `on` key in GitHub Workflows. I would like to have ability to change one config rule for given path.
