### ISSUE TITLE
`truthy` rule false positive

### ISSUE THREAD

**Issue by Pandapip1** [adrienverge/yamllint#671]
Having a key named `on` causes the truthy rule to fail.

Example:

```
name: Continuous Integration

on:  # Error occurs here
  push:
    branches:
      - main
```
