### ISSUE TITLE
Allow a reason comment for disabled rules

### ISSUE THREAD

**Issue by NickLarsenNZ** [adrienverge/yamllint#679]
For example, I want to disable the line limit check for certain files and explain why.
But if I add a comment with the disable, the disable is ignored.

```yaml
# yamllint disable rule:line-length because we want to add links next to some items
```

I propose two options:

1. Add a reason directive, so:
   ```yaml
   # yamllint disable rule:line-length reason:because we want to add links next to some items
   ```
2. Do it in the same way markdownlint does it, and allow an extra comment indicator after:
   ```yaml
   # yamllint disable rule:line-length # because we want to add links next to some items
   ```

After writing them out, I think I prefer the second option (quotes would be superfluous in the first option, yet it looks weird without them).

**Comment by andrewimeson** [comment]
Why not just add a comment on the line above?

```yaml
# Since Bob wrote this ugly YAML, and we miss him, we won’t touch it
# yamllint disable rule:line-length
```

**Comment by NickLarsenNZ** [comment]
> Why not just add a comment on the line above?
> 
> ```yaml
> # Since Bob wrote this ugly YAML, and we miss him, we won’t touch it
> # yamllint disable rule:line-length
> ```

Because I have other comments, and I would like the reason to be tightly coupled with the disabling of the rule.

**Comment by adrienverge** [comment]
Hello!

I like @andrewimeson's proposal because it's handy, and already available :+1:

That being said, the proposed change seems acceptable (I also prefer the second option).

**Comment by andrewimeson** [comment]
>because we want to add links next to some items

This isn't related to your original request, but can you share an example from the file where you need to disable the rule? You may be able to just adjust some of the `line-length` configuration in the yamllint configuration to get what you want, specifically [`allow-non-breakable-inline-mappings`](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.line_length).

**Comment by NickLarsenNZ** [comment]
@andrewimeson, the case I had in mind looked like this (where default line limit is 80 chars, as much as I'd like it longer)...

```yaml
  run_clippy:
    name: Run Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0
        with:
          submodules: recursive

      - uses: dtolnay/rust-toolchain@0e66bd3e6b38ec0ad5312288c83e47c143e6b09e # v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          components: clippy

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ env.GO_VERSION }}

      - uses: Swatinem/rust-cache@23bce251a8cd2ffc3c1075eaa2367cf899916d84 # v2.7.3
        with:
          key: clippy

      - uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 18
          cache: yarn
```

So in this case, we'd like the tag to sit on the same line no matter of length.
