### ISSUE TITLE
Question: Is it possible to enforce an empty line after a multiline string? 

### ISSUE THREAD

**Issue by dandeandean** [adrienverge/yamllint#692]
Hello! I was wondering if it was possible to enforce a newline after a `|` block? 

```yaml
...
bash: |
  ## Bash Script for saying hello to the world
  echo "Hello World"
step: nextstep
...
```

With the output being something like: 
```console
error    not enough blank lines (0 < 1)  (empty-lines)
```

Thank you!
