### ISSUE TITLE
Option to ignore schema comment

### ISSUE THREAD

**Issue by jonsch318** [adrienverge/yamllint#732]
I heavily use the schema comment configuration of the yaml-language-server which looks for example like this 

```yaml
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/refs/heads/main/traefik.io/middleware_v1alpha1.json
apiVersion: traefik.io/v1alpha1
[...]
``` 
The comment can get pretty long due to the urls and then yamllint flags this with `line too long`. 
In general I don't want to disable the line length checks but only say for a comment line that starts with `# yaml-language-server`

**Comment by kquinsland** [comment]
Came here to post exactly this issue!

I have a few dozen files that all start like this:

```yaml
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/prometheus-operator/prometheus-operator/refs/heads/main/jsonnet/prometheus-operator/prometheuses-crd.json # yamllint disable-line rule:line-length
# See: https://prometheus-operator.dev/docs/api-reference/api/#monitoring.coreos.com/v1.Prometheus
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
```

**Note:** I even have the `# yamllint disable-line rule:line-length` there ...

And a `.yamllint.yaml` that looks like this:

```yaml
---
# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
# See: https://yamllint.readthedocs.io/en/stable/configuration.html
##
yaml-files:
  - "*.yaml"
  - "*.yml"
  - ".yamllint"

rules:
 # <...>
  line-length:
    # It's 2025 and 1024x768 isn't a thing anymore.
    max: 140
    # Be strict about this
    level: error
    # Unless it's a URL
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
# <...>
```


And I know that the config file is being loaded because I can change the `140` to `141` and will get lint-failed:

```shell
❯ yamllint some/path/*
some/path/some-file.yaml
  2:141     error    line too long (212 > 141 characters)  (line-length)
```

Change the config back to `140` and the error is adjusted.

SO there's two things here:

1) Something about the `# yaml-language-server: $schema=https://.....` line is breaking the `line-length.allow-non-breakable-words` and `line-length.allow-non-breakable-inline-mappings` settings
2) Something (else?) about that line is breaking the `# yamllint disable-line rule:line-length` parse...
