### ISSUE TITLE
[BUG] Allow `disable-line` to suppress violations caused by itself

### ISSUE THREAD

**Issue by webknjaz** [adrienverge/yamllint#745]
*This is similar to #343 (at least it seems so, I'll let you judge that).*

I have a commented out mapping key (`include:`) that follows an uncommented key (`exclude:`) that has a sequence as a value (specifically `# ` prepended to https://github.com/cherrypy/cherrypy/blob/88987cb/.github/workflows/ci-cd.yml#L604C9-L604C59; it's not yet commented out in the linked commit but is going to be because it makes `check-github-workflows` in https://github.com/python-jsonschema/check-jsonschema unhappy, but that's another story — I'm only mentioning this for context).

I obviously don't want it indented because it'd look like it's a part of the sequence of the previous key, which it isn't.

To facilitate this, I was trying to disable the rule on the line via `# yamllint disable-line rule:comments-indentation` and exceeded the line length. So I tried adding that rule to ignore as well.

My problem is that it didn't work.

Here's the repro:
```yaml
# repro.yml
---
top:
  matrix:
  - some: val
    key: another
  # include: []  # TODO: uncomment blah blah blaaaaaaaaaaah  # yamllint disable-line rule:comments-indentation rule:line-length
```

```console
$ yamllint repro.yml
repro.yml
  6:3       warning  comment not indented like content  (comments-indentation)
  6:81      error    line too long (127 > 80 characters)  (line-length)
```

So it sounds like there's two issues with this:
1) disabling rules doesn't seem to apply to comment lines
2) disabling rules generates more violations

I think that both of these should be thought though: should yamllint auto-suppress line length violations when they are called by `# yamllint` comments? Should it at least apply such suppressions to the comment portions of lines?
