### ISSUE TITLE
Support custom indent for sequences

### ISSUE THREAD

**Issue by psss** [adrienverge/yamllint#757]
Would it be possible to add support for custom number of spaces to be used for indenting sequences? Consider the following example:

```yaml
summary:
    Basic smoke test for the httpd web server
provision:
    how: virtual
    memory: 4096
prepare:
  - name: packages
    how: install
    package: [httpd, curl]
  - name: service
    how: shell
    script: systemctl start httpd
execute:
    how: tmt
    script:
      - echo foo > /var/www/html/index.html
      - curl http://localhost/ | grep foo
```

Or this one:

```yaml
summary:
    Support for multiple configurations
description:
    All steps support multiple configurations. In this way it is
    possible for example to discover tests from multiple repos.
    The 'execute' steps supports only a single configuration.
discover:
  - name: tier0
    how: fmf
    filter: 'tier: 0'
    url: https://github.com/teemtee/tmt
  - name: tier1
    how: fmf
    filter: 'tier: 1'
    url: https://github.com/teemtee/tmt
  - name: all
    how: fmf
    url: https://github.com/teemtee/tmt
prepare:
  - how: ansible
    name: packages
    playbook: ansible/packages.yml
  - how: shell
    name: services
    script: systemctl start service
execute:
    how: tmt
```

I find this way of indenting the sequence content visually in the same way as corresponding dict content as nicely consistent. The values, regardles of their type, all share the same level of indentation. But currently it's not possible with `yamllint` to enforce this.

What about introducing a new config option, let's say `sequence-spaces`, which would allow to specify the number of spaces to be enforced for sequences? Or allow `indent-sequences` to accept an integer which would specify the number of the desire spaces before the `-` character?
